spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_idea
    username: root
    password: Wr040511
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  security:
    basic:
      enabled: false

server:
  port: 8888